version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_auth_api
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  auth-api:
    build: .
    container_name: auth_api
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/authdb?allowPublicKeyRetrieval=true&useSSL=false
    ports:
      - "8080:8080"

volumes:
  mysql_data:
